ENTRY_ACTIVE_CREDITS = {
    "EARN_IMMEDIATE",
    "EARN_ACTIVATE",
    "REDEEM_RETURN_RESTORE",
    "REDEEM_CANCEL_RESTORE",
    "EARN_REVERSE_CANCEL",
    "EARN_CANCEL_RESTORE",
    "OPENING_CREDIT",
    "MANUAL_CREDIT",
}
ENTRY_PENDING_CREDITS = {"EARN_PENDING", "PENDING_REVERSE_CANCEL"}
RESERVATION_ACTIVE_STATES = ("ACTIVE", "PAYMENT_IN_PROGRESS", "PARTIALLY_CONSUMED")
WRITE_FLAG = "ua_loyalty_service"
